{"name": "test_login_success", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2\n  +1\n  -2", "trace": "self = <test_four.TestLogin object at 0x0000028D0EFEC4C8>\n\n    @allure.story('登录成功') # 子功能模块\n    def test_login_success(self):\n        with allure.step(\"步骤1\"):\n            print(\"1、打开菜单\")\n        with allure.step(\"步骤2\"):\n            print(\"2、点击功能\")\n        print('这是登录用例，登录成功')\n>       assert 1==2\nE       assert 1 == 2\nE         +1\nE         -2\n\ntest_four.py:13: AssertionError"}, "steps": [{"name": "步骤1", "status": "passed", "start": 1640492243070, "stop": 1640492243070}, {"name": "步骤2", "status": "passed", "start": 1640492243070, "stop": 1640492243070}], "start": 1640492243070, "stop": 1640492243070, "uuid": "76e4b817-2aac-44e5-a72d-54b9e6aa1734", "historyId": "f302675a2240e46f6fc6f0efcdc1bd5b", "testCaseId": "16d8475c2996ce976bd7fcf89cc4ea92", "fullName": "test_four.TestLogin#test_login_success", "labels": [{"name": "story", "value": "登录成功"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "test_four"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-N0R16UT"}, {"name": "thread", "value": "8248-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_four"}]}